### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hartenthaler** [IsleVision/Chinese-genealogy-webtrees-plugin#1]
I just tried your new module, but this was not successful. 

```
Undefined index: xrefs …/modules_v4/chinese-hanging-report/src/http/PdfPage.php:154
#0 …/modules_v4/chinese-hanging-report/src/http/PdfPage.php(154): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/modules_v4/chinese-hanging-report/src/http/PdfPage.php(99): MyCustomNamespace\http\PdfPage->reportPDF()
#2 …/app/Http/Middleware/WrapHandler.php(66): MyCustomNamespace\http\PdfPage->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process()
#4 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(226): Middleland\Dispatcher->handle()
#5 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process()
#6 …/modules_v4/faces/src/Modules/FacesModule.php(93): Middleland\Dispatcher->handle()
#7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process()
#8 …/modules_v4/family-tree-home/module.php(71): Middleland\Dispatcher->handle()
#9 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): class@anonymous->process()
#10 …/modules_v4/chinese-hanging-report/src/ChineseHangingModule.php(157): Middleland\Dispatcher->handle()
#11 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): MyCustomNamespace\ChineseHangingModule->process()
#12 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()`
```

**Comment by IsleVision** [comment]
I can see from the error log, it seems the individual is not specified in the frontend so that the backend doesn't get the pram. xrefs. It would be helpful for me to debug if you paste how you fill in the frontend entries.

**Comment by hartenthaler** [comment]
I tried to reconstruct the failure, but I don't understand the concept behind your module up to now. So maybe I'm trying to do some stupid things. It would be helpful if you can give some more explanation in the README.
This is how I filled the frontend entries:
![Screenshot (39)](https://user-images.githubusercontent.com/6324175/151057041-afdbf7b1-da87-4d07-93f0-7a1d982b7fcd.png)
I selected my grandmother "Franziska Baumgärtner" and then I was asked to enter "generation levels" (???) for many people in my tree who are not connected to my grandmother. I always entered "1".

And this is the result:
![Screenshot (38)](https://user-images.githubusercontent.com/6324175/151057143-8fc881d0-cc01-4c92-9b31-687023994583.png)


Finally, I was successful to generate a report using another person and other combinations of frontend entries. But the result looks strange for my character set. It is mainly in the direction right to left (or up to down?) and strange character positions.

![Screenshot (35)](https://user-images.githubusercontent.com/6324175/151058090-5431d5fa-cc79-4d8c-bc00-943b0afa3acc.png)

**Comment by IsleVision** [comment]
I'm so sorry. This plugin is designated to develop for Chinese genealogy graph and doesn't support languages other than Chinese. 
The term, hanging line style, is an ancient Chinese genealogy style. Most Chinese names are composed of up to 3 Chinese characters, and in this hanging line style as you can see, name characters are written in the direction top to down, with each character starting in a new line, so they are stacked up; and then print new person to the left/down direction. 
This style is not suitable for western names, simply as your names usually include a lot of characters. In this case, the plugin should be re-developed to accommodate.
I noted your frontend didn't show correctly—in the "show generation level" row, there should be only one input entry. I suppose some other plugins you've installed interfered with this plugin. As you may know, webtrees is not easy to extend, I wrote many js codes to set up the frontend page. If you have some global js codes inserted in this page, the frontend will not display properly.

**Comment by hartenthaler** [comment]
Thank you for your explanation! Maybe you can copy this information to the README.
